version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./mongod.conf:/etc/mongod.conf # Add this line to mount the config file
    command: ["mongod", "--config", "/etc/mongod.conf"] # Use the custom config file

  app:
    build: .
    container_name: app
    ports:
      - "3000:3000"
    depends_on:
      - mongo

volumes:
  mongo-data:
